In [11]:
import torch

In [13]:
tensor = torch.tensor(7)
tensor

tensor(7)

In [14]:
tensor.ndim

0

In [15]:
tensor.item()

7

In [19]:
tensor.shape

torch.Size([])

In [23]:
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [24]:
vector.ndim

1

In [25]:
vector.shape

torch.Size([2])

In [27]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [28]:
matrix.ndim

2

In [30]:
matrix.shape

torch.Size([2, 2])

In [33]:
comp_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
comp_tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
comp_tensor.shape

torch.Size([1, 3, 3])

In [48]:
# create a random 3, 4 size tensor

torch.manual_seed(42) # this gives same random values everytime

tensor_rand = torch.rand((3,4))
tensor_rand, tensor_rand.dtype # default dtype is float32

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 torch.float32)

In [51]:
tensor_rand_big = torch.rand(size=(224, 224, 3), dtype = torch.float32)
tensor_rand_big, tensor_rand_big.ndim

(tensor([[[0.5745, 0.9200, 0.3230],
          [0.8613, 0.0919, 0.3102],
          [0.9536, 0.6002, 0.0351],
          ...,
          [0.6501, 0.1374, 0.3852],
          [0.7029, 0.0650, 0.1280],
          [0.0728, 0.4482, 0.8423]],
 
         [[0.3919, 0.1191, 0.7616],
          [0.9423, 0.8760, 0.9324],
          [0.3308, 0.0646, 0.4916],
          ...,
          [0.4601, 0.4145, 0.8877],
          [0.7979, 0.1490, 0.8975],
          [0.3493, 0.3416, 0.2586]],
 
         [[0.9752, 0.2840, 0.2329],
          [0.7765, 0.1522, 0.3084],
          [0.0165, 0.2109, 0.1842],
          ...,
          [0.7706, 0.6538, 0.3952],
          [0.1024, 0.6485, 0.3496],
          [0.7555, 0.3809, 0.3577]],
 
         ...,
 
         [[0.8716, 0.6351, 0.7019],
          [0.3454, 0.4896, 0.8905],
          [0.9717, 0.3601, 0.9916],
          ...,
          [0.7278, 0.2134, 0.2524],
          [0.1369, 0.8770, 0.7452],
          [0.5307, 0.9066, 0.6534]],
 
         [[0.2118, 0.8450, 0.1104],
          [0

In [55]:
# create a tenor with all zeros and all ones

tensor_zeros = torch.zeros(size=(3, 4))
tensor_ones = torch.ones(size=(3, 4))
tensor_zeros, tensor_zeros.dtype, tensor_ones, tensor_ones.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [60]:
tensor_arange = torch.arange(start=1, end=10, step=1)
tensor_arange = torch.arange(start=1, end=10, step=1).reshape(3, 3)
tensor_arange

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
tensor_zeros_like = torch.zeros_like(input=tensor_arange) # just takes shape from tensor_arange
tensor_ones_like = torch.ones_like(input=tensor_arange)
tensor_zeros_like, tensor_ones_like, tensor_arange

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [67]:
all_value_tensor = torch.tensor([3, 6, 9],
                                dtype = torch.float32,
                                device = None,
                                requires_grad = False)
all_value_tensor, all_value_tensor.shape, all_value_tensor.device, all_value_tensor.grad

(tensor([3., 6., 9.], requires_grad=True),
 torch.Size([3]),
 device(type='cpu'),
 None)

In [70]:
# add, sub, multi, div

tensor_math = torch.tensor([1, 2, 3])
tensor_add = tensor_math + 1 # applies to all values
tensor_sub = tensor_math - 1
tensor_multi = tensor_math * 10
tensor_div = tensor_math / 10

tensor_add, tensor_sub, tensor_multi, tensor_div

(tensor([2, 3, 4]),
 tensor([0, 1, 2]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [76]:
# other ways to do math operations
tensor_math, torch.multiply(tensor_math, 10)

(tensor([1, 2, 3]), tensor([1, 4, 9]))

In [77]:
torch.multiply(tensor_math, tensor_math), tensor_math * tensor_math # same position multiplication 1*1, 2*2, 3*3

(tensor([1, 4, 9]), tensor([1, 4, 9]))

In [86]:
tensor_math @ tensor_math, torch.matmul(tensor_math, tensor_math) # 1*1 + 2*2 + 3*3

(tensor(14), tensor(14))

In [81]:
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)
tensor_A, tensor_B

(tensor([[0.3588, 0.9211, 0.8627, 0.8223],
         [0.5248, 0.5881, 0.2746, 0.3791],
         [0.2975, 0.6450, 0.0163, 0.9160]]),
 tensor([[0.5888, 0.8403, 0.4761, 0.7140],
         [0.4644, 0.6362, 0.8892, 0.1317],
         [0.7164, 0.2706, 0.6560, 0.6614]]))

In [88]:
torch.mm(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T) 

(tensor([[1.9830, 1.6280, 1.6160],
         [1.2046, 0.9120, 0.9659],
         [1.3788, 0.6836, 1.0041]]),
 tensor([[1.9830, 1.6280, 1.6160],
         [1.2046, 0.9120, 0.9659],
         [1.3788, 0.6836, 1.0041]]))

In [92]:
tensor_A.size()

torch.Size([3, 4])

In [95]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=4, out_features=6)

x = tensor_A
linear_x = linear(x)

linear_x.shape, linear_x


(torch.Size([3, 6]),
 tensor([[ 0.4014, -0.1454,  0.1309,  0.0442,  0.1570, -0.5329],
         [ 0.1919, -0.1842,  0.0292, -0.0275,  0.2771, -0.5792],
         [ 0.4055,  0.0670, -0.1539, -0.2078,  0.3225, -0.2997]],
        grad_fn=<AddmmBackward0>))

In [102]:
tensor_arange_2 = torch.arange(0, 100, 10) # 10 is the gap between numbers 
tensor_arange_2

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
tensor_arange_2.max(), tensor_arange_2.min(), tensor_arange_2.sum(), tensor_arange_2.type(torch.float32).mean()

(tensor(90), tensor(0), tensor(450), tensor(45.))

In [107]:
tensor_arange_2.argmax(), tensor_arange_2.argmin() # positions of max and min values

(tensor(9), tensor(0))

In [108]:
tensor_arange_2.dtype

torch.int64

In [110]:
tensor_arange_2_float32 = tensor_arange_2.type(torch.float32)
tensor_arange_2_float32.dtype

torch.float32

In [122]:
# reshaping
x = torch.arange(1, 10, 1)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [126]:
x = x.reshape(shape=[3,3])
x = x.type(torch.float32)
x, x.dtype, x.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32,
 torch.Size([3, 3]))